Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [env.Dir('#include').srcnode()]
components = [
	   'common_grid_util',
	   'share_codec'
	   ]

# --------------------------------------------------------------------------
publicHeaders = [
	      'McrtControl.h',
	      'McrtNodeInfo.h',
	      'McrtNodeInfoMapItem.h'
	      ]
env.DWAInstallInclude(publicHeaders, 'mcrt_dataio/engine/mcrt')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir,LIBS=["ssl"])
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target+["ssl"], CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target+["ssl"],
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
