Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [env.Dir('#include')]
components = [
	   'common_grid_util'
	   ]

# --------------------------------------------------------------------------
publicHeaders = [
	      'SockClient.h',
	      'SockCoreSimple.h',
	      'SockServerConnection.h',
	      'SockServer.h',
	      'SockServerInet.h'
	      ]
env.DWAInstallInclude(publicHeaders, 'mcrt_dataio/share/sock')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir,LIBS=["ssl"])
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target+["ssl"], CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target+["ssl"],
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
