Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [env.Dir('#include').srcnode()]
components = [
	   'common_grid_util',
	   'common_math',
	   'common_platform',
	   'common_rec_time',
	   'denoiser',
	   'engine_merger',
	   'share_codec',
	   'share_util',
	   'mcrt_messages',
	   'message_api',
	   'render_util',
	   'tbb'
	   ]

# --------------------------------------------------------------------------
publicHeaders = [
	      'ClientReceiverConsoleDriver.h',
	      'ClientReceiverFb.h',
	      'TimingRecorderHydra.h'
	      ]
env.DWAInstallInclude(publicHeaders, 'mcrt_dataio/client/receiver')

# We only support building with CUDA in Scons
env['CXXFLAGS'].append('-DMOONRAY_USE_CUDA')

env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir,LIBS=["ssl"])
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target+["ssl"], CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target+["ssl"],
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
